### ISSUE TITLE
머지되지 않은 데이터셋 - 아리마 분석

### ISSUE THREAD

**Issue by pmz-q** [pmz-q/est_wassup_02#13]
- [ ] jupyter notebook 파일에 작성
  - [ ] 머지되기 전 train.csv
- [ ] 아리마 
- [ ] Random Forest & Feature importance 등
  - [ ] 머지되기 전 것 먼저 수행하고 머지된 데이터셋으로 수행해주세요.

**Comment by pmz-q** [comment]
dev-13
dev-13-1

위의 두개의 브랜치로 작업 부탁드립니다.

**Comment by JamieSKinard** [comment]
AutoArima 작업 중 kernel이 죽는 오류 발생

![Image](https://github.com/pmz-q/est_wassup_02/assets/28642545/56fb0299-643f-435f-afaa-4b8ed98bb9fb)

**Comment by JamieSKinard** [comment]
테스트, 트레인 파일 업로드
결측치를 drop하면, ACF, P-ACF 확인 가능
결측치를 앞,뒤로 보고 채우면, ACF, P-ACF 확인 불가
=> 중앙값으로median 하는 코드 작성해야함
+ AutoArima 적용 코드 업데이트 하기 필요
