### ISSUE TITLE
데이터셋 분석 - forecast weather

### ISSUE THREAD

**Issue by pmz-q** [pmz-q/est_wassup_02#20]
데이터셋 칼럼 확인
결측치 확인
describe
전체적인 그래프 확인

**Comment by enversel** [comment]
* 예보는 1시간 전부터 48시간 전인 행이 반복되고 우리는 24시간 전 예보를 사용하기로 함
* 총 행수는 3424512개
* 일자는 637일, 1일당 5376개의 행을 가지고 있다.
* 위도 경도 112가지 경우의 수 * 48 -> 5376
* direct_solar_radiation / surface_solar_radiation_downwards 두 가지 칼럼은 비정상적, 0이 너무 많다.
