### ISSUE TITLE
데이터셋 분석 - client & train

### ISSUE THREAD

**Issue by pmz-q** [pmz-q/est_wassup_02#21]
세그먼트로 나누어서 분석해도 좋고, 
각 column에 대한 분석. 
기존에 하던 EDA입니다.

**Comment by JamieSKinard** [comment]
[링크](https://docs.google.com/document/d/1TRpUoV6J975Fs5Jx3nUrtSJm5yemKx_2FUQ4fc8r1Zg/edit?usp=drive_web&ouid=111653611273195735193)
