### ISSUE TITLE
데이터 양상 정리

### ISSUE THREAD

**Issue by enversel** [pmz-q/est_wassup_02#9]
- [x] 캐글에서 EDA실행한 것들 찾기
- [x] VScode에서 실행
- [x] 인풋값 확인
- [x] 아웃풋값 확인
- [x] 중요해보이는 칼럼 확인

**Comment by pmz-q** [comment]
https://docs.google.com/document/d/1pgvSTXFAnkeJH79wgzy_vtFXRCf1SDFtpfSNdxaqmw4/edit
